version: '3.8'

services:
  backend:
    build: .
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "realtimecollab.asgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://vishnu:vishnu123@db:5432/collabdb  # Optional if you prefer using an environment variable

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: collabdb
      POSTGRES_USER: vishnu
      POSTGRES_PASSWORD: vishnu123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"

volumes:
  postgres_data:
