# Generated by Django 5.0.7 on 2024-07-17 23:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="shared_with",
            field=models.ManyToManyField(
                related_name="shared_documents", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
